
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: node-main
spec:
  type: ClusterIP
  selector:
    app: node-client-main
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
