apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
