# Namespace
namespace: node-main

# Backend Service Configuration
# namespace: node-main

server:
  image: "730335483782.dkr.ecr.us-east-1.amazonaws.com/backend/node-main"
  replicas: 2

client:
  image: "730335483782.dkr.ecr.us-east-1.amazonaws.com/frontend/node-main"
  replicas: 2

mongo:
  uri: "mongodb+srv://keshw:<keshaV@1>@cluster0.bga5f7q.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

ingress:
  enabled: true
  hosts:
    - host: keshavmittal.cloud
      paths:
        - path: /
          backendService: client-service
        - path: /api
          backendService: server-service